# Generated by Django 3.1.7 on 2021-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
