# Generated by Django 3.1.7 on 2021-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
