# Generated by Django 3.1.7 on 2021-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusers_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
