# Generated by Django 3.1.7 on 2021-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusers_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='child',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='father',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='gfather',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='gmother',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='mother',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='spouse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
