# Generated by Django 3.1.7 on 2021-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210727_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=100, null=True),
        ),
    ]
