# Generated by Django 3.1.7 on 2021-07-26 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserSide', '0003_auto_20210726_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to=settings.AUTH_USER_MODEL)),
                ('gfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_father', to=settings.AUTH_USER_MODEL)),
                ('gmother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_mother', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to=settings.AUTH_USER_MODEL)),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to=settings.AUTH_USER_MODEL)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
