# Generated by Django 3.1.7 on 2021-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0005_auto_20210727_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
